# daemonset-2.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset-2
spec:
  selector:
    matchLabels:
      name: daemonset-cloud-2
  template:
    metadata:
      labels:
        name: daemonset-cloud-2
    spec:
      tolerations:
        - effect: NoSchedule
          operator: Exists
      containers:
        - name: daemonset-pod-2
          image: nginx