# wy_web2.yaml

apiVersion: v1
kind: Pod
metadata:
  name: myweb2
spec:
  containers:
    - name: myweb2-nginx
      image: nginx
      ports:
        - containerPort: 80
          protocol: TCP

    - name: myweb2-netshoot
      image: nicolaka/netshoot
      command: ["/bin/bash"]
      args: ["-c", "while t rue; do sleep 5; curmyl localhost; done"]