#restart_onfailure.yaml
apiVersion: v1
kind: Pod
metadata:
  name: completed-pod
spec:
  restartPolicy: OnFailure
  containers:
    - name: completed-pod
      image: busybox
      command: [ "sh" ]
      args: [ "-c", "sleep 5 && exit 1" ]
      # args: [ "-c", "sleep 5 && exit 0" ]


# k apply -f restart_onfailure.yaml && k get pod -w

# always -> 무조건 재시작
# OnFailure -> 실패시 재시작


# exit 1 -> 실패
# exit 0 -> 성공