# service_1.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-service-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-nginx-pod
  template:
    metadata:
      labels:
        app: service-nginx-pod
    spec:
      containers:
        - name: google-samples
          image: gcr.io/google-samples/kubernetes-bootcamp:v1
          ports:
          - containerPort: 8080